= Coder sans peur du changement - Architecture Hexagonale
Présenté à Devoxx France 2015 par Cyrille Martraire https://twitter.com/cyriux/[@cyrius] et Thomas Pierrain https://twitter.com/tpierrain[@tpierrain]
Résumé par https://twitter.com/lgonKlves/[Laurent Goncalves] (e-Citiz Softeam)
:blank:
:navigation:
:toc:
:split:


== Présentation de la session

* Cette session de type Université est une session longue de 3 heures.
* Vous allez me dire 3 heures c'est long ! oui mais en fait non :)
* 3 heures, c'est le temps qu'il faut pour présenter le principe, faire un exercice et confronter les différentes idées.

== L'architecture hexagonale c'est quoi ?

* Le principe de l'architecture hexagonale est de s'assurer du sens des dépendances : Dependency Inversion Principle
* Isoler le modèle métier afin qu'il ne dépende pas de la technique et du monde extérieur.

== Les avantages ?

* Un modèle isolé est très facile à faire évoluer, refactorer, ...
* Il est également très facile de rajouter des connecteurs avec le monde extérieur sans casser l'existant

== Comment faire ?

* Mettre en place le http://en.wikipedia.org/wiki/Dependency_inversion_principle[DIP Principle]
* Mettre en place des interfaces dès que le domaine (notre modèle fonctionnel central) a besoin de s'interfacer avec le monde extérieur
* Un Adapter, externe à notre modèle, implémentera alors cette interface et permettra de connecter la librairie externe

